export default {
    PROGRAMMING_CATEGORY:"PROGRAMMING_CATEGORY",
    DESIGN_CATEGORY:"DESIGN_CATEGORY",
    BUSINESS_CATEGORY:"BUSINESS_CATEGORY",
    LANGUAGE_CATEGORY:"LANGUAGE_CATEGORY",
    NONE_CATEGORY:"NONE_CATEGORY",
    GET_TEACHERS:"GET_TEACHERS",
    GET_COURSES:"GET_COURSES",
    GET_PROGRAMMING_COURSES:"GET_PROGRAMMING_COURSES",
    GET_BUSINESS_COURSES:"GET_BUSINESS_COURSES",
    GET_DESIGN_COURSES:"GET_DESIGN_COURSES",
    GET_LANGUAGE_COURSES:"GET_LANGUAGE_COURSES",
    PENDING:"_PENDING",
    FULFILLED:"_FULFILLED",
    REJECTED:"_REJECTED",
    COURSES_LIST:"COURSES_LIST"
}